<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-9AI18F1" name="com.PageLibrary.com.Ranford.TestExecution" tests="6" failures="0" timestamp="4 Sep 2018 11:06:02 GMT" time="25.022" errors="1">
  <testcase name="launch_Browser" time="17.314" classname="com.PageLibrary.com.Ranford.TestExecution"/>
  <testcase name="verify_login" time="2.906" classname="com.PageLibrary.com.Ranford.TestExecution"/>
  <testcase name="click_NewBranch" time="1.781" classname="com.PageLibrary.com.Ranford.TestExecution"/>
  <testcase name="newBranch_Operations" time="2.562" classname="com.PageLibrary.com.Ranford.TestExecution"/>
  <testcase name="click_Branches" time="0.219" classname="com.PageLibrary.com.Ranford.TestExecution"/>
  <testcase name="validate_excel" time="0.240" classname="com.PageLibrary.com.Ranford.TestExecution">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at excel.Excel.ccount(Excel.java:44)
	at com.PageLibrary.com.Ranford.TestExecution.validate_excel(TestExecution.java:93)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- validate_excel -->
</testsuite> <!-- com.PageLibrary.com.Ranford.TestExecution -->
